# 开发环境配置
server:
  port: 8801
  servlet:
    # 应用的访问路径
    context-path: /verify
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8

wx:
  appid: wx7d97660308fba004
  secret: 7110ee10356b3e20f7f94f6546ac175d
spring:
  redis:
    # 改成自己redis的ip地址
    host: 112.74.107.161
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        # 最大阻塞等待时间(负数表示没限制)
        max-active: 20
        max-wait: -1
    password: Prodadmin123
  datasource:
    url: jdbc:mysql://112.74.107.161:3306/aipower?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Prodadmin123
    driver-class-name: com.mysql.cj.jdbc.Driver
